### ISSUE TITLE
Automatically color new pulls.

### ISSUE THREAD

**Issue by Nnoggie** [Nnoggie/MethodDungeonTools#114]
Base the coloring on a color scheme. Maybe user selectable?
![img](https://i.imgur.com/xEROYIs.png "")

**Comment by Espen-Storvold** [comment]
Suggestion for color scheme:

Alternating between warm and cold color gradients. 
To give clear indicator as to what NPC's goes into each pull, when looking at the map.

Example (first 10, but ofcourse go through the entire wheel and starting at "1" again):
![image](https://user-images.githubusercontent.com/38696945/66330471-c2f44080-e930-11e9-8be9-2e79f1c0450e.png)

**Comment by Urtgard** [comment]
In action: https://www.youtube.com/watch?v=G380OJUVhGY

**Comment by ESpmdark** [comment]
@Urtgard 
Just need to ask, as it might be me misunderstanding.
Ref. your video:
Will we no longer be able to mark a pull, and add mobs directly into it? As such, will we have to merge pulls in the list instead?

If so, it might cause too much extra work for the user when editing MDT runs.

The color options though looks perfect 👍

**Comment by Urtgard** [comment]
You mean like this?

![mdt1](https://user-images.githubusercontent.com/13890391/71644512-d6157300-2cc9-11ea-96af-3674821b50c0.gif)

**Comment by ESpmdark** [comment]
Yes, like that. Good :)
I guess you used shift-clicking in the first video. I completely forgot about that keybind.

**Comment by zmoose** [comment]
How do you get it to color automatically?  I'm doing shift+click and it makes new pulls but not coloring anything automatically.

**Comment by Nnoggie** [comment]
implemented in https://github.com/Nnoggie/MethodDungeonTools/pull/141
