### ISSUE TITLE
Feature Request: Support for Classic Dungeons

### ISSUE THREAD

**Issue by willcodeforfood** [Nnoggie/MethodDungeonTools#127]
It'd be really neat to be able to plan all my pulls in 5 man Classic WoW dungeons using this tool.

When they bring back the infamous "45 minute Baron run" in a later phase of Classic, MDT will be invaluable. In the meantime, it would be useful for low level runs where I'm grinding for exp and gear.

Are there any official plans to add this functionality to the addon?

**Comment by Nnoggie** [comment]
never going to happen
