### ISSUE TITLE
Angry triangle

### ISSUE THREAD

**Issue by madar2252** [Nnoggie/MethodDungeonTools#138]
The week warning triangle went crazy since the 8.3 update. Whenever I change between the dungeons, it's unpredictable what the triangle thinks. For example I look TD, set week3, and then change to Underrot which also set as week3, and the triangle unhappy. Then I change to Siege which is set as week2, and he is perfectly fine with it. His friend, the green marker of the week number is always accurate tho.

![image](https://user-images.githubusercontent.com/42252230/73594318-88309c80-450d-11ea-9625-53eb9431c547.png)

**Comment by Stinth** [comment]
As far as I could see the issue arose from moving away from using SetAffixWeek() since the OnValueChanged function associated with the affixDropdown is not called when affixDropdown:SetValue() is used.
This fix makes the AffixWeekWarning toggling work similarly to that of the difficultyWarning.

**Comment by Nnoggie** [comment]
fixed in https://github.com/Nnoggie/MethodDungeonTools/pull/141
