### ISSUE TITLE
% bug teeming shrine

### ISSUE THREAD

**Issue by CyberT33N** [Nnoggie/MethodDungeonTools#140]
as it seems the % are wrong for teeming on shrine, we did correct route but missed 10% at end

not sure if its only for shrine or other dungeons too

**Comment by CyberT33N** [comment]
edit also for tol dagor I got 2x obelisk at start area

**Comment by Nnoggie** [comment]
fixed in 9cb8dcbc41b6c45ae44af5e008dc3c52d5dfc15b
