### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Rowie73** [Nnoggie/MethodDungeonTools#142]
I have uninstalled and reinstalled turned all add ons of and ran it deleted the saved variables settings in my WTF folder and im still getting my MDT showing like this. Has anyone had any other issues similar or this one in particular?
![MDT](https://user-images.githubusercontent.com/63948984/79682824-ca45c080-8268-11ea-8798-5b54a812196d.PNG)

**Comment by Nnoggie** [comment]
install bugsack/buggrabber and post error logs please

**Comment by Rowie73** [comment]
Hi,
I managed to do a complete fresh install of the client and it sorted the issue out. If it happens again i will do that. Cheers for the respose
