### ISSUE TITLE
Wrong number of enemy. ML-G30

### ISSUE THREAD

**Issue by mr-aleks** [Nnoggie/MethodDungeonTools#143]
I noticed that this week (Tyrannical, Bolstering, Explosive, Awakened), the number of enemies in the G30 pack is incorrectly indicated. In reality, there are fewer of them. Mech Jockey is already in the robot and does not give enemy forces for itself but only for the word, apparently. All this can be easily checked in the video below.
https://www.twitch.tv/videos/617844268?t=05h51m28s
Screenshot, how the addon shows it now.
![image](https://user-images.githubusercontent.com/23143866/81692098-8e1c0f00-9466-11ea-8ae1-10eecae038f1.png)
PS. Sorry for my english as i use translator

**Comment by SilentSigns** [comment]
This is not a bug it is what the note on the exclamation marks are referring to, they are left in because they are apparently technically possible to tag before they die. 

Realistically you'll just want to remember that detail and ctrl+click jockey 21 and 22 out of your routes.
