### ISSUE TITLE
Missing Grease Bot on the map in Junkyard

### ISSUE THREAD

**Issue by razko** [Nnoggie/MethodDungeonTools#145]
There's a Grease Bot in Mechagon: Junkyard that is not shown on the MDT map:
Map location: https://i.imgur.com/Lbg64jh.jpg
Ingame view: https://i.imgur.com/AjMd6KA.jpg

**Comment by Nnoggie** [comment]
what version of mdt are you running?

**Comment by Nnoggie** [comment]
fixed in 3.0.5
