### ISSUE TITLE
Addon isn't working

### ISSUE THREAD

**Issue by Csanta1985** [Nnoggie/MethodDungeonTools#148]
When I open my addon in game i just get a black screen that pops up. I tried deleting and re installing the addon and it hasn't changed. Everything is updated and i'm lost at what the problem could be. Any insight would be greatly appreciated
![Mdt](https://user-images.githubusercontent.com/66955033/84661263-b7094700-aedf-11ea-8f86-820b52b17cd8.png)

**Comment by DennyScott** [comment]
@Csanta1985 I had the same issue occur today. You can't trigger it in dev mode, it has to specifically in the regular mode. There is a workaround I found though to get back into a good state. When you first do a `/reload`, you should be able to see some initial parts of the UI (but not all of it) when you open mdt. Try right clicking a pull on the right side and selecting "Reset Preset". You may need to open and close mdt again, but you should be back into a good state.

@Nnoggie So the issue that is happening here is in this line. https://github.com/Nnoggie/MethodDungeonTools/blame/885c6c6edcdabef6b779c4aa4ebe60c95d5f2b31/MethodDungeonTools.lua#L3817. I'll paste the actual stack trace for you:

```
16x ...aceMethodDungeonTools\MethodDungeonTools-3.0.5.lua:3759: attempt to index field '?' (a nil value)
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:3759: in function `PickPullButton'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:3737: in function `ReloadPullButtons'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:2702: in function `UpdateMap'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:1430: in function `SetAffixWeek'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:4864: in function <...aceMethodDungeonTools\MethodDungeonTools.lua:4653>
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:546: in function `ShowInterface'
[string "@MethodDungeonTools\MethodDungeonTools-3.0.5.lua"]:34: in function `OnClick'
[string "@Bartender4\libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:144: in function `oclick'
[string "@MBB\MBB-4.0.1.lua"]:408: in function <MBB\MBB.lua:396>
```

I'm not super familiar with the code, so I just ran some WA custom functions against it. In my case, `self:GetCurrentPreset().value.currentPull` was set to 32, despite there only being 30 pulls in my current dungeon. My best guess, someone else in live mode deleted some pulls but somehow my current selection wasn't updated to the newest last? I tried testing against that but could not trigger it again

**Comment by Nnoggie** [comment]
Thank you for the insight @DennyScott 
I need more info on how this issue arises, i cannot seem to be able to reproduce the error.
This snippet is supposed to deal with this iregularity:
https://github.com/Nnoggie/MethodDungeonTools/blame/885c6c6edcdabef6b779c4aa4ebe60c95d5f2b31/MethodDungeonTools.lua#L2664-L2667
@Csanta1985 
Navigate to World of Warcraft_retail_\WTF\Account<ACCOUNTNUMBER>\SavedVariables and send the file MethodDungeonTools.lua to me. For a quick fix you can close the game and  delete this file and MethodDungeonTools.lua.bak

**Comment by Nnoggie** [comment]
@Csanta1985 newest version v3.0.8 should have your bug resolved
